language: node_js
node_js: stable

services:
  - postgresql

before_script:
  - psql -c 'create database pokemon_test;' -U postgres
  - psql -c 'create table trainers (id serial, name varchar);' -U postgres -d pokemon_test
  - psql -c "insert into trainers (name) values ('Saïd');" -U postgres -d pokemon_test

after_success:
  - npm run coveralls
