language: node_js
node_js: stable

services:
  - postgresql

before_script:
  - psql -c 'create database pokemon_test;' -U postgres
  - psql -c 'create table trainers (id serial);' -U postgres -d pokemon_test
